# This config file is templatized so that it can be easily customized. Values can be provided with a values.yml at the root of this repository
template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: go_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      branches:
        include: main
      gitProvider: {{ .Values.gitProvider }}


  # Build info for the published Go app
  - name: go_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}


  - name: checker
    type: FileSpec
    configuration:
      sourceArtifactory: b
      pattern: checker_files/*



pipelines:
  - name: do_source_check
    steps:
      - name: source_check
        type: Bash
        configuration:
          inputResources:
            - name: go_repo
              trigger: true
            - name: checker
              trigger: false

        execution:
          onStart:
            - cd dependencyState/resources/checker/
            - ls ../go_repo/*.go > files_to_scan.txt
            - ls --recursive            
            - cat dependencyState/resources/checker/files_to_scan.txt
            - converter -in files_to_scan.txt
            - python simple_dfa_poc.py package_ssa.json
            - ls --recursive

          onSuccess:
            - echo "Done"
          onFailure:
            - echo "Fail"


  - name: go_build_pipeline_example
    steps:
      # Build the Go sample app from the GitRepo. Docs at https://www.jfrog.com/confluence/display/JFROG/GoBuild
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          resolverRepo: a-go-virtual
          noRegistry: true
          inputResources:
            - name: go_repo
          integrations:
            - name: {{ .Values.artifactory }}

      # Publish the Go sample app binary to Artifactory. Docs at https://www.jfrog.com/confluence/display/JFROG/GoPublishBinary
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_go
          targetRepository: a-go-local
          integrations:
            - name: {{ .Values.artifactory }}

      # Publish the Go sample app build info. Docs at https://www.jfrog.com/confluence/display/JFROG/PublishBuildInfo
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binary
          outputResources:
            - name: go_buildinfo